application: cacophon-demo
runtime: go
module: backend-golang
version: 1
api_version: go1
vm: true

manual_scaling:
  instances: 1

vm_settings:
  apt_get_install: lame

handlers:
- url: /.*
  script: _go_app
