application: cacophon-app
runtime: go
module: backend
version: 1
api_version: go1
vm: true

manual_scaling:
  instances: 1

vm_settings:
  preserve_vm_on_failure: true
  apt_get_install: lame

handlers:
- url: /audio
  script: _go_app

