application: cacophon-demo
module: frontend
version: 1
runtime: docker://localhost:5000/proppy/cacophon-frontend
api_version: 1
vm: true

manual_scaling:
  instances: 1

vm_settings:
  docker_bucket: cacophon-images
  preserve_vm_on_failure: true

handlers:
- url: /.*
  script: server.js
