application: cacophon-demo
module: backend
version: 1
runtime: docker://localhost:5000/proppy/cacophon-demo-backend
api_version: go1
vm: true

manual_scaling:
  instances: 1

vm_settings:
  docker_bucket: cacophon-images
  preserve_vm_on_failure: true

handlers:
- url: /audio
  script: _go_app
